version: 2
updates:
  - package-ecosystem: npm
    directory: "/flipt-node"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"

  - package-ecosystem: pip
    directory: "/flipt-python"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"

  - package-ecosystem: "cargo"
    directory: "/flipt-rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"

  - package-ecosystem: gradle
    directory: "/flipt-java"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
