version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/flipt-node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ["*"]
      npm-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/flipt-python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      pip-security:
        applies-to: security-updates
        patterns: ["*"]
      pip-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "cargo"
    directory: "/flipt-rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      cargo-security:
        applies-to: security-updates
        patterns: ["*"]
      cargo-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "gradle"
    directory: "/flipt-java"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      gradle-security:
        applies-to: security-updates
        patterns: ["*"]
      gradle-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    groups:
      github-actions:
        patterns: ["*"]
