name: Package Java SDK
on:
  push:
    tags: ["flipt-java-**"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to package (e.g., flipt-java-v1.3.0). Leave empty to use latest tag."
        required: false
        type: string

permissions:
  contents: write

env:
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  MAVEN_PUBLISH_REGISTRY_URL: ${{ secrets.MAVEN_PUBLISH_REGISTRY_URL }}
  PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  build:
    uses: ./.github/workflows/package-sdks.yml
    with:
      sdk: java
      tag: ${{ inputs.tag || github.ref }}
    secrets: inherit
