name: Package PHP SDK
on:
  push:
    tags: ["flipt-php-**"]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/package-sdks.yml
    with:
      sdk: php
    secrets: inherit
