name: Package Python SDK
on:
  push:
    tags: ["flipt-python-**"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to package (e.g., flipt-python-v1.5.0). Leave empty to use latest tag."
        required: false
        type: string

permissions:
  contents: write

env:
  PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/package-sdks.yml
    with:
      sdk: python
      tag: ${{ inputs.tag || github.ref }}
    secrets: inherit
