name: Package C# SDK
on:
  push:
    tags: ["flipt-csharp-**"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to package (e.g., flipt-csharp-v0.1.1). Leave empty to use latest tag."
        required: false
        type: string

permissions:
  contents: write

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/package-sdks.yml
    with:
      sdk: csharp
      tag: ${{ inputs.tag || github.ref }}
    secrets: inherit
